spring:
server:
    port: 8762
    wait-time-in-ms-when-sync-empty: 0
eureka:
   client:
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://localhost:8762/eureka
     
      
  
